name: Test Results
run-name: Test Results (${{ github.event.workflow.name }}) [${{ github.event.workflow_run.event }}]

on:
  workflow_run:
    workflows:
      - 'C\+\+'
      - 'C#'
      - 'NodeJS'
      - 'Python'
    types:
      - completed
permissions: {}

jobs:
  test-results:
    name: Test Results
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion != 'skipped'

    permissions:
      # required to create check status
      checks: write

      # required to write comment to pull request
      pull-requests: write

      # required by download step to access artifacts API
      actions: read

    steps:
      - name: Download event file
        uses: dawidd6/action-download-artifact@07ab29fd4a977ae4d2b275087cf67563dfdf0295  # v9
        with:
           run_id: ${{ github.event.workflow_run.id }}
           name: Event
           path: artifacts

      - name: Download test results
        uses: dawidd6/action-download-artifact@07ab29fd4a977ae4d2b275087cf67563dfdf0295  # v9
        with:
           run_id: ${{ github.event.workflow_run.id }}
           name: ^test-results-.*
           name_is_regexp: true
           path: artifacts

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          commit: ${{ github.event.workflow_run.head_sha }}
          check_name: Test Results (${{ github.event.workflow.name }}) [${{ github.event.workflow_run.event }}]
          comment_mode: ${{ github.event.workflow_run.event == 'pull_request' && 'always' || 'off' }}
          event_file: artifacts/Event/event.json
          event_name: ${{ github.event.workflow_run.event }}
          files: "artifacts/**/*.xml"
